/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mvx_common_jni_Secp256k1 */

#ifndef _Included_com_mvx_common_jni_Secp256k1
#define _Included_com_mvx_common_jni_Secp256k1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mvx_common_jni_Secp256k1
 * Method:    init_context
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_mvx_common_jni_Secp256k1_init_1context
  (JNIEnv *, jclass);

/*
 * Class:     com_mvx_common_jni_Secp256k1
 * Method:    ecdsa_verify
 * Signature: (Ljava/nio/ByteBuffer;JII)I
 */
JNIEXPORT jint JNICALL Java_com_mvx_common_jni_Secp256k1_ecdsa_1verify
  (JNIEnv *, jclass, jobject, jlong, jint, jint);

/*
 * Class:     com_mvx_common_jni_Secp256k1
 * Method:    ecdsa_sign
 * Signature: (Ljava/nio/ByteBuffer;J)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_mvx_common_jni_Secp256k1_ecdsa_1sign
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_mvx_common_jni_Secp256k1
 * Method:    ecdsa_verify2
 * Signature: (Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_com_mvx_common_jni_Secp256k1_ecdsa_1verify2
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     com_mvx_common_jni_Secp256k1
 * Method:    ecdsa_sign2
 * Signature: (Ljava/nio/ByteBuffer;)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_com_mvx_common_jni_Secp256k1_ecdsa_1sign2
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
